from django.shortcuts import render
import joblib
import numpy as np
import pandas as pd

# Create your views here.


def home(request):
    return render(request, 'webpages/home.html')


def about(request):
    return render(request, 'webpages/about.html')


def contact(request):
    return render(request, 'webpages/contact.html')


def result(request):
    model = joblib.load('finalizedmodel.sav')

    form = []
    form.append(float(request.GET['year']))
    form.append(float(request.GET['Kilometers']))
    form.append(float(request.GET['Owner']))
    form.append(float(request.GET['mileage']))
    form.append(float(request.GET['engine']))
    form.append(float(request.GET['power']))
    form.append(float(request.GET['seats']))
    form.append(request.GET['car'])
    form.append(request.GET['location'])
    form.append(request.GET['fuel'])

    arr = ['Year',
           'Kilometers_Driven',
           'Owner_Type',
           'Mileage',
           'Engine',
           'Power',
           'Seats',
           'Cars_Audi A3',
           'Cars_Audi A4',
           'Cars_Audi A6',
           'Cars_Audi A7',
           'Cars_Audi A8',
           'Cars_Audi Q3',
           'Cars_Audi Q5',
           'Cars_Audi Q7',
           'Cars_Audi RS5',
           'Cars_Audi TT',
           'Cars_BMW 1',
           'Cars_BMW 3',
           'Cars_BMW 5',
           'Cars_BMW 6',
           'Cars_BMW 7',
           'Cars_BMW X1',
           'Cars_BMW X3',
           'Cars_BMW X5',
           'Cars_BMW X6',
           'Cars_BMW Z4',
           'Cars_Bentley Continental',
           'Cars_Chevrolet Aveo',
           'Cars_Chevrolet Beat',
           'Cars_Chevrolet Captiva',
           'Cars_Chevrolet Cruze',
           'Cars_Chevrolet Enjoy',
           'Cars_Chevrolet Optra',
           'Cars_Chevrolet Sail',
           'Cars_Chevrolet Spark',
           'Cars_Chevrolet Tavera',
           'Cars_Datsun GO',
           'Cars_Datsun Redi',
           'Cars_Datsun redi-GO',
           'Cars_Fiat Avventura',
           'Cars_Fiat Grande',
           'Cars_Fiat Linea',
           'Cars_Fiat Petra',
           'Cars_Fiat Punto',
           'Cars_Fiat Siena',
           'Cars_Force One',
           'Cars_Ford Aspire',
           'Cars_Ford Classic',
           'Cars_Ford Ecosport',
           'Cars_Ford Endeavour',
           'Cars_Ford Fiesta',
           'Cars_Ford Figo',
           'Cars_Ford Freestyle',
           'Cars_Ford Fusion',
           'Cars_Ford Ikon',
           'Cars_Ford Mustang',
           'Cars_Honda Accord',
           'Cars_Honda Amaze',
           'Cars_Honda BR-V',
           'Cars_Honda BRV',
           'Cars_Honda Brio',
           'Cars_Honda CR-V',
           'Cars_Honda City',
           'Cars_Honda Civic',
           'Cars_Honda Jazz',
           'Cars_Honda Mobilio',
           'Cars_Honda WR-V',
           'Cars_Honda WRV',
           'Cars_Hyundai Accent',
           'Cars_Hyundai Creta',
           'Cars_Hyundai EON',
           'Cars_Hyundai Elantra',
           'Cars_Hyundai Elite',
           'Cars_Hyundai Getz',
           'Cars_Hyundai Grand',
           'Cars_Hyundai Santa',
           'Cars_Hyundai Santro',
           'Cars_Hyundai Sonata',
           'Cars_Hyundai Tucson',
           'Cars_Hyundai Verna',
           'Cars_Hyundai Xcent',
           'Cars_Hyundai i10',
           'Cars_Hyundai i20',
           'Cars_ISUZU D-MAX',
           'Cars_Isuzu MUX',
           'Cars_Jaguar F',
           'Cars_Jaguar XE',
           'Cars_Jaguar XF',
           'Cars_Jaguar XJ',
           'Cars_Jeep Compass',
           'Cars_Lamborghini Gallardo',
           'Cars_Land Rover',
           'Cars_Mahindra Bolero',
           'Cars_Mahindra Jeep',
           'Cars_Mahindra KUV',
           'Cars_Mahindra Logan',
           'Cars_Mahindra NuvoSport',
           'Cars_Mahindra Quanto',
           'Cars_Mahindra Renault',
           'Cars_Mahindra Scorpio',
           'Cars_Mahindra Ssangyong',
           'Cars_Mahindra TUV',
           'Cars_Mahindra Thar',
           'Cars_Mahindra Verito',
           'Cars_Mahindra XUV300',
           'Cars_Mahindra XUV500',
           'Cars_Mahindra Xylo',
           'Cars_Maruti 1000',
           'Cars_Maruti 800',
           'Cars_Maruti A-Star',
           'Cars_Maruti Alto',
           'Cars_Maruti Baleno',
           'Cars_Maruti Celerio',
           'Cars_Maruti Ciaz',
           'Cars_Maruti Dzire',
           'Cars_Maruti Eeco',
           'Cars_Maruti Ertiga',
           'Cars_Maruti Esteem',
           'Cars_Maruti Grand',
           'Cars_Maruti Ignis',
           'Cars_Maruti Omni',
           'Cars_Maruti Ritz',
           'Cars_Maruti S',
           'Cars_Maruti S-Cross',
           'Cars_Maruti SX4',
           'Cars_Maruti Swift',
           'Cars_Maruti Versa',
           'Cars_Maruti Vitara',
           'Cars_Maruti Wagon',
           'Cars_Maruti Zen',
           'Cars_Mercedes-Benz A',
           'Cars_Mercedes-Benz B',
           'Cars_Mercedes-Benz C-Class',
           'Cars_Mercedes-Benz CLA',
           'Cars_Mercedes-Benz CLS-Class',
           'Cars_Mercedes-Benz E-Class',
           'Cars_Mercedes-Benz GL-Class',
           'Cars_Mercedes-Benz GLA',
           'Cars_Mercedes-Benz GLC',
           'Cars_Mercedes-Benz GLE',
           'Cars_Mercedes-Benz GLS',
           'Cars_Mercedes-Benz M-Class',
           'Cars_Mercedes-Benz New',
           'Cars_Mercedes-Benz R-Class',
           'Cars_Mercedes-Benz S',
           'Cars_Mercedes-Benz S-Class',
           'Cars_Mercedes-Benz SL-Class',
           'Cars_Mercedes-Benz SLC',
           'Cars_Mercedes-Benz SLK-Class',
           'Cars_Mini Clubman',
           'Cars_Mini Cooper',
           'Cars_Mini Countryman',
           'Cars_Mitsubishi Cedia',
           'Cars_Mitsubishi Lancer',
           'Cars_Mitsubishi Montero',
           'Cars_Mitsubishi Outlander',
           'Cars_Mitsubishi Pajero',
           'Cars_Nissan Evalia',
           'Cars_Nissan Micra',
           'Cars_Nissan Sunny',
           'Cars_Nissan Teana',
           'Cars_Nissan Terrano',
           'Cars_Nissan X-Trail',
           'Cars_Porsche Boxster',
           'Cars_Porsche Cayenne',
           'Cars_Porsche Cayman',
           'Cars_Porsche Panamera',
           'Cars_Renault Captur',
           'Cars_Renault Duster',
           'Cars_Renault Fluence',
           'Cars_Renault KWID',
           'Cars_Renault Koleos',
           'Cars_Renault Lodgy',
           'Cars_Renault Pulse',
           'Cars_Renault Scala',
           'Cars_Skoda Fabia',
           'Cars_Skoda Laura',
           'Cars_Skoda Octavia',
           'Cars_Skoda Rapid',
           'Cars_Skoda Superb',
           'Cars_Skoda Yeti',
           'Cars_Smart Fortwo',
           'Cars_Tata Bolt',
           'Cars_Tata Hexa',
           'Cars_Tata Indica',
           'Cars_Tata Indigo',
           'Cars_Tata Manza',
           'Cars_Tata Nano',
           'Cars_Tata New',
           'Cars_Tata Nexon',
           'Cars_Tata Safari',
           'Cars_Tata Sumo',
           'Cars_Tata Tiago',
           'Cars_Tata Tigor',
           'Cars_Tata Venture',
           'Cars_Tata Xenon',
           'Cars_Tata Zest',
           'Cars_Toyota Camry',
           'Cars_Toyota Corolla',
           'Cars_Toyota Etios',
           'Cars_Toyota Fortuner',
           'Cars_Toyota Innova',
           'Cars_Toyota Platinum',
           'Cars_Toyota Qualis',
           'Cars_Volkswagen Ameo',
           'Cars_Volkswagen Beetle',
           'Cars_Volkswagen CrossPolo',
           'Cars_Volkswagen Jetta',
           'Cars_Volkswagen Passat',
           'Cars_Volkswagen Polo',
           'Cars_Volkswagen Tiguan',
           'Cars_Volkswagen Vento',
           'Cars_Volvo S60',
           'Cars_Volvo S80',
           'Cars_Volvo V40',
           'Cars_Volvo XC60',
           'Cars_Volvo XC90',
           'Location_Bangalore',
           'Location_Chennai',
           'Location_Coimbatore',
           'Location_Delhi',
           'Location_Hyderabad',
           'Location_Jaipur',
           'Location_Kochi',
           'Location_Kolkata',
           'Location_Mumbai',
           'Location_Pune',
           'Fuel_Type_Diesel',
           'Fuel_Type_LPG',
           'Fuel_Type_Petrol']

    user_input = []
    user_input.append(form[0])
    user_input.append(form[1])
    user_input.append(form[2])
    user_input.append(form[3])
    user_input.append(form[4])
    user_input.append(form[5])
    user_input.append(form[6])

    for i in range(7, 218):
        if form[7] not in arr[i]:
            user_input.append(0)
        else:
            user_input.append(1)

    for i in range(218, 228):
        if form[8] not in arr[i]:
            user_input.append(0)
        else:
            user_input.append(1)

    for i in range(228, 231):
        if form[9] not in arr[i]:
            user_input.append(0)
        else:
            user_input.append(1)

    user_input = np.array(user_input)

    df = pd.DataFrame([user_input], columns=['Year',
                                             'Kilometers_Driven',
                                             'Owner_Type',
                                             'Mileage',
                                             'Engine',
                                             'Power',
                                             'Seats',
                                             'Cars_Audi A3',
                                             'Cars_Audi A4',
                                             'Cars_Audi A6',
                                             'Cars_Audi A7',
                                             'Cars_Audi A8',
                                             'Cars_Audi Q3',
                                             'Cars_Audi Q5',
                                             'Cars_Audi Q7',
                                             'Cars_Audi RS5',
                                             'Cars_Audi TT',
                                             'Cars_BMW 1',
                                             'Cars_BMW 3',
                                             'Cars_BMW 5',
                                             'Cars_BMW 6',
                                             'Cars_BMW 7',
                                             'Cars_BMW X1',
                                             'Cars_BMW X3',
                                             'Cars_BMW X5',
                                             'Cars_BMW X6',
                                             'Cars_BMW Z4',
                                             'Cars_Bentley Continental',
                                             'Cars_Chevrolet Aveo',
                                             'Cars_Chevrolet Beat',
                                             'Cars_Chevrolet Captiva',
                                             'Cars_Chevrolet Cruze',
                                             'Cars_Chevrolet Enjoy',
                                             'Cars_Chevrolet Optra',
                                             'Cars_Chevrolet Sail',
                                             'Cars_Chevrolet Spark',
                                             'Cars_Chevrolet Tavera',
                                             'Cars_Datsun GO',
                                             'Cars_Datsun Redi',
                                             'Cars_Datsun redi-GO',
                                             'Cars_Fiat Avventura',
                                             'Cars_Fiat Grande',
                                             'Cars_Fiat Linea',
                                             'Cars_Fiat Petra',
                                             'Cars_Fiat Punto',
                                             'Cars_Fiat Siena',
                                             'Cars_Force One',
                                             'Cars_Ford Aspire',
                                             'Cars_Ford Classic',
                                             'Cars_Ford Ecosport',
                                             'Cars_Ford Endeavour',
                                             'Cars_Ford Fiesta',
                                             'Cars_Ford Figo',
                                             'Cars_Ford Freestyle',
                                             'Cars_Ford Fusion',
                                             'Cars_Ford Ikon',
                                             'Cars_Ford Mustang',
                                             'Cars_Honda Accord',
                                             'Cars_Honda Amaze',
                                             'Cars_Honda BR-V',
                                             'Cars_Honda BRV',
                                             'Cars_Honda Brio',
                                             'Cars_Honda CR-V',
                                             'Cars_Honda City',
                                             'Cars_Honda Civic',
                                             'Cars_Honda Jazz',
                                             'Cars_Honda Mobilio',
                                             'Cars_Honda WR-V',
                                             'Cars_Honda WRV',
                                             'Cars_Hyundai Accent',
                                             'Cars_Hyundai Creta',
                                             'Cars_Hyundai EON',
                                             'Cars_Hyundai Elantra',
                                             'Cars_Hyundai Elite',
                                             'Cars_Hyundai Getz',
                                             'Cars_Hyundai Grand',
                                             'Cars_Hyundai Santa',
                                             'Cars_Hyundai Santro',
                                             'Cars_Hyundai Sonata',
                                             'Cars_Hyundai Tucson',
                                             'Cars_Hyundai Verna',
                                             'Cars_Hyundai Xcent',
                                             'Cars_Hyundai i10',
                                             'Cars_Hyundai i20',
                                             'Cars_ISUZU D-MAX',
                                             'Cars_Isuzu MUX',
                                             'Cars_Jaguar F',
                                             'Cars_Jaguar XE',
                                             'Cars_Jaguar XF',
                                             'Cars_Jaguar XJ',
                                             'Cars_Jeep Compass',
                                             'Cars_Lamborghini Gallardo',
                                             'Cars_Land Rover',
                                             'Cars_Mahindra Bolero',
                                             'Cars_Mahindra Jeep',
                                             'Cars_Mahindra KUV',
                                             'Cars_Mahindra Logan',
                                             'Cars_Mahindra NuvoSport',
                                             'Cars_Mahindra Quanto',
                                             'Cars_Mahindra Renault',
                                             'Cars_Mahindra Scorpio',
                                             'Cars_Mahindra Ssangyong',
                                             'Cars_Mahindra TUV',
                                             'Cars_Mahindra Thar',
                                             'Cars_Mahindra Verito',
                                             'Cars_Mahindra XUV300',
                                             'Cars_Mahindra XUV500',
                                             'Cars_Mahindra Xylo',
                                             'Cars_Maruti 1000',
                                             'Cars_Maruti 800',
                                             'Cars_Maruti A-Star',
                                             'Cars_Maruti Alto',
                                             'Cars_Maruti Baleno',
                                             'Cars_Maruti Celerio',
                                             'Cars_Maruti Ciaz',
                                             'Cars_Maruti Dzire',
                                             'Cars_Maruti Eeco',
                                             'Cars_Maruti Ertiga',
                                             'Cars_Maruti Esteem',
                                             'Cars_Maruti Grand',
                                             'Cars_Maruti Ignis',
                                             'Cars_Maruti Omni',
                                             'Cars_Maruti Ritz',
                                             'Cars_Maruti S',
                                             'Cars_Maruti S-Cross',
                                             'Cars_Maruti SX4',
                                             'Cars_Maruti Swift',
                                             'Cars_Maruti Versa',
                                             'Cars_Maruti Vitara',
                                             'Cars_Maruti Wagon',
                                             'Cars_Maruti Zen',
                                             'Cars_Mercedes-Benz A',
                                             'Cars_Mercedes-Benz B',
                                             'Cars_Mercedes-Benz C-Class',
                                             'Cars_Mercedes-Benz CLA',
                                             'Cars_Mercedes-Benz CLS-Class',
                                             'Cars_Mercedes-Benz E-Class',
                                             'Cars_Mercedes-Benz GL-Class',
                                             'Cars_Mercedes-Benz GLA',
                                             'Cars_Mercedes-Benz GLC',
                                             'Cars_Mercedes-Benz GLE',
                                             'Cars_Mercedes-Benz GLS',
                                             'Cars_Mercedes-Benz M-Class',
                                             'Cars_Mercedes-Benz New',
                                             'Cars_Mercedes-Benz R-Class',
                                             'Cars_Mercedes-Benz S',
                                             'Cars_Mercedes-Benz S-Class',
                                             'Cars_Mercedes-Benz SL-Class',
                                             'Cars_Mercedes-Benz SLC',
                                             'Cars_Mercedes-Benz SLK-Class',
                                             'Cars_Mini Clubman',
                                             'Cars_Mini Cooper',
                                             'Cars_Mini Countryman',
                                             'Cars_Mitsubishi Cedia',
                                             'Cars_Mitsubishi Lancer',
                                             'Cars_Mitsubishi Montero',
                                             'Cars_Mitsubishi Outlander',
                                             'Cars_Mitsubishi Pajero',
                                             'Cars_Nissan Evalia',
                                             'Cars_Nissan Micra',
                                             'Cars_Nissan Sunny',
                                             'Cars_Nissan Teana',
                                             'Cars_Nissan Terrano',
                                             'Cars_Nissan X-Trail',
                                             'Cars_Porsche Boxster',
                                             'Cars_Porsche Cayenne',
                                             'Cars_Porsche Cayman',
                                             'Cars_Porsche Panamera',
                                             'Cars_Renault Captur',
                                             'Cars_Renault Duster',
                                             'Cars_Renault Fluence',
                                             'Cars_Renault KWID',
                                             'Cars_Renault Koleos',
                                             'Cars_Renault Lodgy',
                                             'Cars_Renault Pulse',
                                             'Cars_Renault Scala',
                                             'Cars_Skoda Fabia',
                                             'Cars_Skoda Laura',
                                             'Cars_Skoda Octavia',
                                             'Cars_Skoda Rapid',
                                             'Cars_Skoda Superb',
                                             'Cars_Skoda Yeti',
                                             'Cars_Smart Fortwo',
                                             'Cars_Tata Bolt',
                                             'Cars_Tata Hexa',
                                             'Cars_Tata Indica',
                                             'Cars_Tata Indigo',
                                             'Cars_Tata Manza',
                                             'Cars_Tata Nano',
                                             'Cars_Tata New',
                                             'Cars_Tata Nexon',
                                             'Cars_Tata Safari',
                                             'Cars_Tata Sumo',
                                             'Cars_Tata Tiago',
                                             'Cars_Tata Tigor',
                                             'Cars_Tata Venture',
                                             'Cars_Tata Xenon',
                                             'Cars_Tata Zest',
                                             'Cars_Toyota Camry',
                                             'Cars_Toyota Corolla',
                                             'Cars_Toyota Etios',
                                             'Cars_Toyota Fortuner',
                                             'Cars_Toyota Innova',
                                             'Cars_Toyota Platinum',
                                             'Cars_Toyota Qualis',
                                             'Cars_Volkswagen Ameo',
                                             'Cars_Volkswagen Beetle',
                                             'Cars_Volkswagen CrossPolo',
                                             'Cars_Volkswagen Jetta',
                                             'Cars_Volkswagen Passat',
                                             'Cars_Volkswagen Polo',
                                             'Cars_Volkswagen Tiguan',
                                             'Cars_Volkswagen Vento',
                                             'Cars_Volvo S60',
                                             'Cars_Volvo S80',
                                             'Cars_Volvo V40',
                                             'Cars_Volvo XC60',
                                             'Cars_Volvo XC90',
                                             'Location_Bangalore',
                                             'Location_Chennai',
                                             'Location_Coimbatore',
                                             'Location_Delhi',
                                             'Location_Hyderabad',
                                             'Location_Jaipur',
                                             'Location_Kochi',
                                             'Location_Kolkata',
                                             'Location_Mumbai',
                                             'Location_Pune',
                                             'Fuel_Type_Diesel',
                                             'Fuel_Type_LPG',
                                             'Fuel_Type_Petrol'])

    ans = round(model.predict(df)[0], 2)

    data = {
        'result': ans,
        'inputs': form
    }

    return render(request, 'webpages/result.html', data)
